### ISSUE TITLE
Inflation txout naming

### ISSUE THREAD

**Issue by fedsten** [rgb-org/spec#113]
In the header of the contract there is an optional field called `inflation_txout`, which is used when a secondary issuance has to be performed. Wouldn't it be clearer if it was called simply `secondary_issuance_txout`? I would avoid using different terms to express the same concept when it's not strictly necessary.

**Comment by dr-orlovsky** [comment]
My point was to keep variable names short... And the core difference is that contract is issuing assets under `issuance_txout`, while `secondary_issuance_txout` is reserved for future contracts, i.e. they are not of the same “type”, if I can say that way. 

But for surr we can change the name if you still see it as a better option. Pls keep in mind, that v1.0 will invalidate these names anyway...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
