### ISSUE TITLE
Add reference and link to LNPBP repo?

### ISSUE THREAD

**Issue by msgilligan** [rgb-org/spec#117]
Should we add a note and/or link to the new repo https://github.com/LNP-BP/lnpbps so people will know that this repo is obsolete and where to find the newer documents?

**Comment by dr-orlovsky** [comment]
Sure, done, with some explanations

**Comment by msgilligan** [comment]
> Sure, done, with some explanations

Looks good but I would change the following:

> RGB is a based on a stack of LNP/BP standards

to:

> RGB is a based on a suite of LNP/BP standards

Stack generally refers to an implementation of the standards, suite usually refers to the standards themselves.

**Comment by msgilligan** [comment]
I also submitted a PR with some readability improvements:

https://github.com/rgb-org/spec/pull/118
