### ISSUE TITLE
https://rgb.network is down / not resolving

### ISSUE THREAD

**Issue by GlenCooper** [rgb-org/spec#119]
This link is broken and should be updated: https://rgb.network/

![20200110T060651Z-rgb_network_down](https://user-images.githubusercontent.com/967793/72130056-49754f80-3370-11ea-9836-d6ebc1f3e9f7.png)

**Comment by GlenCooper** [comment]
Looks like the domain is not registered.  I'm thinking about snatching it before someone bad does.

> mrbtc@1satoshi:~$ whois rgb.network
> Domain not found.
> This premium domain is available for purchase. If you would like to make an offer, please contact platinums@donuts.email.
> >>> Last update of WHOIS database: 2020-01-10T06:11:10Z <<<
> 
> Terms of Use: Donuts Inc. provides this Whois service for information purposes, and to assist persons in obtaining information about or related to a domain name registration record. Donuts does not guarantee its accuracy. Users accessing the Donuts Whois service agree to use the data only for lawful purposes, and under no circumstances may this data be used to: a) allow, enable, or otherwise support the transmission by e-mail, telephone, or facsimile of mass unsolicited, commercial advertising or solicitations to entities other than the registrar’s own existing customers and b) enable high volume, automated, electronic processes that send queries or data to the systems of Donuts or any ICANN-accredited registrar, except as reasonably necessary to register domain names or modify existing registrations. When using the Donuts Whois service, please consider the following: The Whois service is not a replacement for standard EPP commands to the SRS service. Whois is not considered authoritative for registered domain objects. The Whois service may be scheduled for downtime during production or OT&E maintenance periods. Queries to the Whois services are throttled. If too many queries are received from a single IP address within a specified time, the service will begin to reject further queries for a period of time to prevent disruption of Whois service access. Abuse of the Whois system through data mining is mitigated by detecting and limiting bulk query access from single sources. Where applicable, the presence of a [Non-Public Data] tag indicates that such data is not made publicly available due to applicable data privacy laws or requirements. Should you wish to contact the registrant, please refer to the Whois records available through the registrar URL listed above. Access to non-public data may be provided, upon request, where it can be reasonably confirmed that the requester holds a specific legitimate interest and a proper legal basis for accessing the withheld da
> ta. Access to this data can be requested by submitting a request via the form found at https://donuts.domains/about/policies/whois-layered-access/ Donuts Inc. reserves the right to modify these terms at any time. By submitting this query, you agree to abide by this policy.
> mrbtc@1satoshi:~$ 
>

**Comment by GlenCooper** [comment]
I'm hunting you, Giacomo Zucco.

**Comment by dr-orlovsky** [comment]
I've done this on behalf of LNP/BP Standards Association which is supervising RGB development for now. Thanks for pointing that out! We will work on some website for it soon.

**Comment by barnardstar** [comment]
Glad to see this project is still alive

**Comment by GlenCooper** [comment]
Thanks @dr-orlovsky 

![BL8jLsxfEOBgamtX_oIP8bh13FrOmgJOjMEud4ZPJ9M](https://user-images.githubusercontent.com/967793/72198050-784afe80-3420-11ea-8c40-b726473dcef0.gif)


I've confirmed the "rgb.network" domain name is now registered.

> mrbtc@1satoshi:~$ date
> Sat Jan 11 03:09:00 GMT 2020
> mrbtc@1satoshi:~$ whois rgb.network
> Domain Name: rgb.network
> Registry Domain ID: d57e012798a146128aca2885f6e89733-DONUTS
> Registrar WHOIS Server: whois.godaddy.com/
> Registrar URL: http://www.godaddy.com/domains/search.aspx?ci=8990
> Updated Date: 2020-01-10T11:01:51Z
> Creation Date: 2020-01-10T11:01:50Z
> Registry Expiry Date: 2021-01-10T11:01:50Z
> Registrar: GoDaddy.com, LLC
> Registrar IANA ID: 146
> Registrar Abuse Contact Email: abuse@godaddy.com
> Registrar Abuse Contact Phone: +1.4806242505
> Domain Status: clientDeleteProhibited https://icann.org/epp#clientDeleteProhibited
> Domain Status: clientRenewProhibited https://icann.org/epp#clientRenewProhibited
> Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
> Domain Status: clientUpdateProhibited https://icann.org/epp#clientUpdateProhibited
> Domain Status: addPeriod https://icann.org/epp#addPeriod
> Registry Registrant ID: REDACTED FOR PRIVACY
> Registrant Name: REDACTED FOR PRIVACY
> Registrant Organization: Domains By Proxy, LLC
> Registrant Street: REDACTED FOR PRIVACY
> Registrant City: REDACTED FOR PRIVACY
> Registrant State/Province: Arizona
> Registrant Postal Code: REDACTED FOR PRIVACY
> Registrant Country: US
> Registrant Phone: REDACTED FOR PRIVACY
> Registrant Phone Ext: REDACTED FOR PRIVACY
> Registrant Fax: REDACTED FOR PRIVACY
> Registrant Fax Ext: REDACTED FOR PRIVACY
> Registrant Email: Please query the RDDS service of the Registrar of Record identified in this output for information on how to contact the Registrant, Admin, or Tech contact of the queried domain name.
> Registry Admin ID: REDACTED FOR PRIVACY
> Admin Name: REDACTED FOR PRIVACY
> Admin Organization: REDACTED FOR PRIVACY
> Admin Street: REDACTED FOR PRIVACY
> Admin City: REDACTED FOR PRIVACY
> Admin State/Province: REDACTED FOR PRIVACY
> Admin Postal Code: REDACTED FOR PRIVACY
> Admin Country: REDACTED FOR PRIVACY
> Admin Phone: REDACTED FOR PRIVACY
> Admin Phone Ext: REDACTED FOR PRIVACY
> Admin Fax: REDACTED FOR PRIVACY
> Admin Fax Ext: REDACTED FOR PRIVACY
> Admin Email: Please query the RDDS service of the Registrar of Record identified in this output for information on how to contact the Registrant, Admin, or Tech contact of the queried domain name.
> Registry Tech ID: REDACTED FOR PRIVACY
> Tech Name: REDACTED FOR PRIVACY
> Tech Organization: REDACTED FOR PRIVACY
> Tech Street: REDACTED FOR PRIVACY
> Tech City: REDACTED FOR PRIVACY
> Tech State/Province: REDACTED FOR PRIVACY
> Tech Postal Code: REDACTED FOR PRIVACY
> Tech Country: REDACTED FOR PRIVACY
> Tech Phone: REDACTED FOR PRIVACY
> Tech Phone Ext: REDACTED FOR PRIVACY
> Tech Fax: REDACTED FOR PRIVACY
> Tech Fax Ext: REDACTED FOR PRIVACY
> Tech Email: Please query the RDDS service of the Registrar of Record identified in this output for information on how to contact the Registrant, Admin, or Tech contact of the queried domain name.
> Name Server: ns21.domaincontrol.com
> Name Server: ns22.domaincontrol.com
> DNSSEC: unsigned
> URL of the ICANN Whois Inaccuracy Complaint Form: https://www.icann.org/wicf/
> >>> Last update of WHOIS database: 2020-01-11T03:09:04Z <<<
> 
> For more information on Whois status codes, please visit https://icann.org/epp
> 
> Terms of Use: Donuts Inc. provides this Whois service for information purposes, and to assist persons in obtaining information about or related to a domain name registration record. Donuts does not guarantee its accuracy. Users accessing the Donuts Whois service agree to use the data only for lawful purposes, and under no circumstances may this data be used to: a) allow, enable, or otherwise support the transmission by e-mail, telephone, or facsimile of mass unsolicited, commercial advertising or solicitations to entities other than the registrar’s own existing customers and b) enable high volume, automated, electronic processes that send queries or data to the systems of Donuts or any ICANN-accredited registrar, except as reasonably necessary to register domain names or modify existing registrations. When using the Donuts Whois service, please consider the following: The Whois service is not a replacement for standard EPP commands to the SRS service. Whois is not considered authoritative for registered domain objects. The Whois service may be scheduled for downtime during production or OT&E maintenance periods. Queries to the Whois services are throttled. If too many queries are received from a single IP address within a specified time, the service will begin to reject further queries for a period of time to prevent disruption of Whois service access. Abuse of the Whois system through data mining is mitigated by detecting and limiting bulk query access from single sources. Where applicable, the presence of a [Non-Public Data] tag indicates that such data is not made publicly available due to applicable data privacy laws or requirements. Should you wish to contact the registrant, please refer to the Whois records available through the registrar URL listed above. Access to non-public data may be provided, upon request, where it can be reasonably confirmed that the requester holds a specific legitimate interest and a proper legal basis for accessing the withheld data. Access to this data can be requested by submitting a request via the form found at https://donuts.domains/about/policies/whois-layered-access/ Donuts Inc. reserves the right to modify these terms at any time. By submitting this query, you agree to abide by this policy.
> mrbtc@1satoshi:~$ 
> 

I'm closing out this issue.

**Comment by GlenCooper** [comment]
Thanks @dr-orlovsky.   I've confirmed the "rgb.network" domain name is now registered.
 
> mrbtc@1satoshi:\~$ date
> Sat Jan 11 03:09:00 GMT 2020
> mrbtc@1satoshi:~$ whois rgb.network
> Domain Name: rgb.network
> Registry Domain ID: d57e012798a146128aca2885f6e89733-DONUTS
> Registrar WHOIS Server: whois.godaddy.com/
> Registrar URL: http://www.godaddy.com/domains/search.aspx?ci=8990
> Updated Date: 2020-01-10T11:01:51Z
> Creation Date: 2020-01-10T11:01:50Z
> Registry Expiry Date: 2021-01-10T11:01:50Z
> Registrar: GoDaddy.com, LLC
> Registrar IANA ID: 146
> Registrar Abuse Contact Email: abuse@godaddy.com
> Registrar Abuse Contact Phone: +1.4806242505
> Domain Status: clientDeleteProhibited https://icann.org/epp#clientDeleteProhibited
> Domain Status: clientRenewProhibited https://icann.org/epp#clientRenewProhibited
> Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
> Domain Status: clientUpdateProhibited https://icann.org/epp#clientUpdateProhibited
> Domain Status: addPeriod https://icann.org/epp#addPeriod
> Registry Registrant ID: REDACTED FOR PRIVACY
> Registrant Name: REDACTED FOR PRIVACY
> Registrant Organization: Domains By Proxy, LLC
> Registrant Street: REDACTED FOR PRIVACY
> Registrant City: REDACTED FOR PRIVACY
> Registrant State/Province: Arizona
> Registrant Postal Code: REDACTED FOR PRIVACY
> Registrant Country: US
> Registrant Phone: REDACTED FOR PRIVACY
> Registrant Phone Ext: REDACTED FOR PRIVACY
> Registrant Fax: REDACTED FOR PRIVACY
> Registrant Fax Ext: REDACTED FOR PRIVACY
> Registrant Email: Please query the RDDS service of the Registrar of Record identified in this output for information on how to contact the Registrant, Admin, or Tech contact of the queried domain name.
> Registry Admin ID: REDACTED FOR PRIVACY
> Admin Name: REDACTED FOR PRIVACY
> Admin Organization: REDACTED FOR PRIVACY
> Admin Street: REDACTED FOR PRIVACY
> Admin City: REDACTED FOR PRIVACY
> Admin State/Province: REDACTED FOR PRIVACY
> Admin Postal Code: REDACTED FOR PRIVACY
> Admin Country: REDACTED FOR PRIVACY
> Admin Phone: REDACTED FOR PRIVACY
> Admin Phone Ext: REDACTED FOR PRIVACY
> Admin Fax: REDACTED FOR PRIVACY
> Admin Fax Ext: REDACTED FOR PRIVACY
> Admin Email: Please query the RDDS service of the Registrar of Record identified in this output for information on how to contact the Registrant, Admin, or Tech contact of the queried domain name.
> Registry Tech ID: REDACTED FOR PRIVACY
> Tech Name: REDACTED FOR PRIVACY
> Tech Organization: REDACTED FOR PRIVACY
> Tech Street: REDACTED FOR PRIVACY
> Tech City: REDACTED FOR PRIVACY
> Tech State/Province: REDACTED FOR PRIVACY
> Tech Postal Code: REDACTED FOR PRIVACY
> Tech Country: REDACTED FOR PRIVACY
> Tech Phone: REDACTED FOR PRIVACY
> Tech Phone Ext: REDACTED FOR PRIVACY
> Tech Fax: REDACTED FOR PRIVACY
> Tech Fax Ext: REDACTED FOR PRIVACY
> Tech Email: Please query the RDDS service of the Registrar of Record identified in this output for information on how to contact the Registrant, Admin, or Tech contact of the queried domain name.
> Name Server: ns21.domaincontrol.com
> Name Server: ns22.domaincontrol.com
> DNSSEC: unsigned
> URL of the ICANN Whois Inaccuracy Complaint Form: https://www.icann.org/wicf/
> >>> Last update of WHOIS database: 2020-01-11T03:09:04Z <<<
> 
> For more information on Whois status codes, please visit https://icann.org/epp
> 
> Terms of Use: Donuts Inc. provides this Whois service for information purposes, and to assist persons in obtaining information about or related to a domain name registration record. Donuts does not guarantee its accuracy. Users accessing the Donuts Whois service agree to use the data only for lawful purposes, and under no circumstances may this data be used to: a) allow, enable, or otherwise support the transmission by e-mail, telephone, or facsimile of mass unsolicited, commercial advertising or solicitations to entities other than the registrar’s own existing customers and b) enable high volume, automated, electronic processes that send queries or data to the systems of Donuts or any ICANN-accredited registrar, except as reasonably necessary to register domain names or modify existing registrations. When using the Donuts Whois service, please consider the following: The Whois service is not a replacement for standard EPP commands to the SRS service. Whois is not considered authoritative for registered domain objects. The Whois service may be scheduled for downtime during production or OT&E maintenance periods. Queries to the Whois services are throttled. If too many queries are received from a single IP address within a specified time, the service will begin to reject further queries for a period of time to prevent disruption of Whois service access. Abuse of the Whois system through data mining is mitigated by detecting and limiting bulk query access from single sources. Where applicable, the presence of a [Non-Public Data] tag indicates that such data is not made publicly available due to applicable data privacy laws or requirements. Should you wish to contact the registrant, please refer to the Whois records available through the registrar URL listed above. Access to non-public data may be provided, upon request, where it can be reasonably confirmed that the requester holds a specific legitimate interest and a proper legal basis for accessing the withheld data. Access to this data can be requested by submitting a request via the form found at https://donuts.domains/about/policies/whois-layered-access/ Donuts Inc. reserves the right to modify these terms at any time. By submitting this query, you agree to abide by this policy.
> mrbtc@1satoshi:~$ 
> 

I'm closing out this issue.
