### ISSUE TITLE
Add support for eltoo

### ISSUE THREAD

**Issue by afilini** [rgb-org/spec#22]
I was thinking about how we could add support for eltoo-style lightning network channels. 

Initially I was pretty sure that we would need to implement our own "noinput" signature format, but now I'm wondering if we really need to explicitly add the input proofs to a new proof we are creating: it's actually implicit, while we spend a specific UTXO we can "plug in" as inputs all the proofs that are bound to this UTXO and there's no need to add a "previous proof hash" into a new proof.

This would obviously imply an out-of-the-box support for eltoo in RGB, since there are no "inputs" in a signed proof that would need to be updated later on.

**Comment by dr-orlovsky** [comment]
Why did you closed this issue?
