### ISSUE TITLE
Technical debt of dual commitment schemes

### ISSUE THREAD

**Issue by fedsten** [rgb-org/spec#62]
Current protocol specifications define two separate commitment schemes for proofs and contracts, one using OP_RETURN and the other using pay-to-contract. While pay-to-contract offers obvious and significant advantages, it is unclear if there is any use case in which OP_RETURN would be preferable.
If p2c ends up being always superior, I don't see the point of having an alternative commitment scheme which would only cause a burden for wallet developers who will have to keep compatibility with both schemes, even if only one is widely used.

**Comment by dr-orlovsky** [comment]
Good reason for OP_RETURN is provided by @tomt1664:

> Getting pay-to-contract to work with hardware wallets is non-trivial. Getting pay-to-contract to work with with most off-the-shelf HSMs (that are typically used by exchanges etc for custody) is impossible. Restricting RGB to pay-to-contract/sign-to-contract only may limit the applicability and use cases.
