### ISSUE TITLE
Why does contract deployment require OP_RETURN?

### ISSUE THREAD

**Issue by Sjors** [rgb-org/spec#66]
The [spec says](https://github.com/rgb-org/spec/blob/master/01-rgb.md#commitment-scheme:

> Every contract MUST be deployed using the OP_RETURN scheme, independently from which commitment_scheme is set.

Why is this? Is this expected to change in a future version? This would be useful to clarify in the spec.

**Comment by dr-orlovsky** [comment]
Have to note, that the actual code in pay-to-contract branch provides the functionality to deploy the contract also in P2C scheme

**Comment by dr-orlovsky** [comment]
Closing since the issue is fixed with the PR #71
