### ISSUE TITLE
Why transfer proofs needs asset id field?

### ISSUE THREAD

**Issue by dr-orlovsky** [rgb-org/spec#72]
The spec suggests that the transaction proofs need to contain triplets for each output with a specified color of the token being transacted (i.e. asset id = hash of the serialized contract).

This is redundant, since each proof is linked to a single asset, so there is no need to provide asset id information within output fields for the proofs

**Comment by dr-orlovsky** [comment]
Seems like I found an answer: for some contract blueprints (like Crowdsale) there might be multiple type of assets issued under the same contract. Thus, asset id field is required. However, in this case, it is unclear from the spec how different asset ids are assigned and supported.

**Comment by inaltoasinistra** [comment]
The send to utxo feature enables to send different asset types to a utxo

**Comment by dr-orlovsky** [comment]
@giacomozucco can you pls confirm my understanding of the issue?

**Comment by giacomozucco** [comment]
Yes, I can confirm:
- as you said, a single contract could be used to issue multiple asset types,
- as @inaltoasinistra said, a single UTXO could receive different asset types.

Furthermore, there are some (still very speculative) ideas to improve privacy and compactability of proves in multi-asset scenarios, by aggregating the parts of the proof which are not strictly needed to verify the absence of double-spending on one specific asset (for example the proofs about other unrelated assets) in a MMR-like structure. In general, I would say the triplets are not redundant.

**Comment by dr-orlovsky** [comment]
How different assets issued by under the same RGB contract should be identified? It's clearly not the hash of the contract itself (since it is constant), and there are no fields in the issuance contract to identify the issued assets

**Comment by dr-orlovsky** [comment]
Replaced by #85
