### ISSUE TITLE
No support for spending single RGB output from the proof

### ISSUE THREAD

**Issue by dr-orlovsky** [rgb-org/spec#94]
In the current spec the proof can contain multiple outputs with different amount of RGB assets in each. However, the input part of the proof references the whole previous proof which it spends, not a particular proof output. Thus, if Alice sends 1000 USD₮ to Bob and 500USD₮ to Carol, both Bob and Carol can't spend their own assets without spending assets of the other party.

The same is true for the original librgb code. Am I missing something?

**Comment by inaltoasinistra** [comment]
The assets are binded to the UTXO, not to the proof.
The `input` array inside the proof refers to the whole proof, but the bitcoin transaction spends the UTXO.

Bob and Carol will use the same proof, but they spend different UTXOs, so different assets

**Comment by dr-orlovsky** [comment]
Correct, sorry, it was a silly question
